<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CalculatorLibrary\CalculatorLibrary.csproj" />
	<PackageReference Include="Microsoft.CognitiveServices.Speech" Version="1.48.2" />
	<PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.5" />
	  <PackageReference Include="Spectre.Console" Version="0.54.0" />
	<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.5" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.Development.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
